version: '3'
services:
  web:
    build: ./src
    ports: 
      - "5000:5000"
    volumes:
      - ./src:/code
    environment:
      FLASK_ENV: development

  mysqldb:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD:password
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
